# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typecrawl < Formula
  desc "A terminal typing test with RPG-style progression (XP, achievements, HP/combo mechanics)."
  homepage "https://github.com/jmatelli/typecrawl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmatelli/typecrawl/releases/download/v0.1.0/typecrawl_0.1.0_darwin_x86_64.tar.gz"
      sha256 "b62cb781161cfa7bec4e812da06d18c311c5e57881ac1bb9b0c3813816047939"

      define_method(:install) do
        bin.install "typecrawl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmatelli/typecrawl/releases/download/v0.1.0/typecrawl_0.1.0_darwin_arm64.tar.gz"
      sha256 "6dc929b002216eb6ed3affe5a02fbedb9d60111bbd1818175ff15387353754da"

      define_method(:install) do
        bin.install "typecrawl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmatelli/typecrawl/releases/download/v0.1.0/typecrawl_0.1.0_linux_x86_64.tar.gz"
      sha256 "f41d1480e3fb742551ccc3a0edb14f9176d77d686f73ee8d7b4929ab84b0bdf3"
      define_method(:install) do
        bin.install "typecrawl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmatelli/typecrawl/releases/download/v0.1.0/typecrawl_0.1.0_linux_arm64.tar.gz"
      sha256 "354101638d03c183070fe28ab3292f3f95f8b4580f802efcd85ea43798a1c566"
      define_method(:install) do
        bin.install "typecrawl"
      end
    end
  end

  test do
    system "#{bin}/typecrawl", "--list-profiles"
  end
end
